### ISSUE TITLE
"python manager.py runserver" fails

### ISSUE THREAD

**Issue by mushketyk** [levlaz/braindump#155]
Current version of project in the "master" branch fails to run with the following error:

```
(env)(master) % python manage.py runserver                                                                                                                                           ~/Development/braindump
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    from app import create_app, db
  File "/home/proger/Development/braindump/app/__init__.py", line 18, in <module>
    github=oauth.remote_app('github',**GITHUB_SETTINGS)
  File "/home/proger/Development/braindump/env/local/lib/python2.7/site-packages/flask_oauthlib/client.py", line 71, in remote_app
    remote = OAuthRemoteApp(self, name, **kwargs)
  File "/home/proger/Development/braindump/env/local/lib/python2.7/site-packages/flask_oauthlib/client.py", line 272, in __init__
    "OAuthRemoteApp requires consumer key and secret"
TypeError: OAuthRemoteApp requires consumer key and secret
```

**Comment by levlaz** [comment]
@mushketyk since we introduced GitHub Auth we need to export some ENVARS. 

If you want to test out OAuth, make your own GitHub app and export the following: 

```
export GITHUB_CONSUMER_KEY='$KEY'
export GITHUB_CONSUMER_SECRET='$SECRET'
```

If you don't care about GitHub Auth, just export some dummy data: 

```
export GITHUB_CONSUMER_KEY='TEST'
export GITHUB_CONSUMER_SECRET='TEST'
```
