### ISSUE TITLE
500 Error when Note does not exist 

### ISSUE THREAD

**Issue by levlaz** [levlaz/braindump#205]
```
Exception on /tasks [GET]
Traceback (most recent call last):
 File "/var/www/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
   response = self.full_dispatch_request()
 File "/var/www/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/var/www/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/var/www/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
   rv = self.dispatch_request()
 File "/var/www/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/var/www/env/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
   return func(*args, **kwargs)
 File "/var/www/app/main/views.py", line 388, in tasks
   return render_template('app/tasks.html', tasks=tasks)
 File "/var/www/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
   context, ctx.app)
 File "/var/www/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
   rv = template.render(context)
 File "/var/www/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
   return self.environment.handle_exception(exc_info, True)
 File "/var/www/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "/var/www/app/templates/app/tasks.html", line 3, in top-level template code
   {% import "_macros.html" as macros %}
 File "/var/www/app/templates/app/app_base.html", line 1, in top-level template code
   {% extends 'bootstrap/base.html' %}
 File "/var/www/env/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
   {% block doc -%}
 File "/var/www/env/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
   {%- block html %}
 File "/var/www/env/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
   {% block body -%}
 File "/var/www/env/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
   {% block content -%}
 File "/var/www/app/templates/app/app_base.html", line 73, in block "content"
   {% block page_content %}{% endblock %}
 File "/var/www/app/templates/app/tasks.html", line 40, in block "page_content"
   <a href="{{ url_for('main.note', id=task.get_note().id) }}">{{ task.get_note().title }}</a>
 File "/var/www/env/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
   force_external=external)
 File "/var/www/env/lib/python2.7/site-packages/werkzeug/routing.py", line 1756, in build
   rv = self._partial_build(endpoint, values, method, append_unknown)
 File "/var/www/env/lib/python2.7/site-packages/werkzeug/routing.py", line 1671, in _partial_build
   append_unknown)
 File "/var/www/env/lib/python2.7/site-packages/werkzeug/routing.py", line 1679, in _partial_build
   rv = rule.build(values, append_unknown)
 File "/var/www/env/lib/python2.7/site-packages/werkzeug/routing.py", line 798, in build
   add(self._converters[data].to_url(values[data]))
 File "/var/www/env/lib/python2.7/site-packages/werkzeug/routing.py", line 1016, in to_url
   value = self.num_convert(value)
UndefinedError: 'None' has no attribute 'id'
```

**Comment by levlaz** [comment]
This happens when a note is deleted with a tasks still attached. 

When a note is deleted, the task should be updated to remove the note_id
