### ISSUE TITLE
Searching on braindump.pw is broken

### ISSUE THREAD

**Issue by felicianotech** [levlaz/braindump#266]
Just returns a "Server Error".

**Comment by levlaz** [comment]
Finally got mail logging working again, stack trace below: 

---
Exception on /search [GET]
Traceback (most recent call last):
 File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
   response = self.full_dispatch_request()
 File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
   raise value
 File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
   rv = self.dispatch_request()
 File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/usr/local/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
   return func(*args, **kwargs)
 File "/usr/src/app/app/main/views.py", line 271, in search
   notes=results)
 File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
   context, ctx.app)
 File "/usr/local/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
   rv = template.render(context)
 File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
   return self.environment.handle_exception(exc_info, True)
 File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
   raise value.with_traceback(tb)
 File "/usr/src/app/app/templates/app/search.html", line 2, in top-level template code
   {% import "bootstrap/wtf.html" as wtf %}
 File "/usr/src/app/app/templates/app/app_base.html", line 1, in top-level template code
   {% extends 'bootstrap/base.html' %}
 File "/usr/local/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
   {% block doc -%}
 File "/usr/local/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
   {%- block html %}
 File "/usr/local/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
   {% block body -%}
 File "/usr/local/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
   {% block content -%}
 File "/usr/src/app/app/templates/app/app_base.html", line 62, in block "content"
   {% block page_content %}{% endblock %}
 File "/usr/src/app/app/templates/app/search.html", line 16, in block "page_content"
   {% include 'app/_notes.html' %}
 File "/usr/src/app/app/templates/app/_notes.html", line 6, in top-level template code
   {{ moment(note.updated_date).format("MMMM D, YYYY") }}
jinja2.exceptions.UndefinedError: 'moment' is undefined

This got broken during the move from flask-moment to managing all JS assets separate from flask.
